name: Build desktop apps (mac x64/arm64 + win)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # LTS, stabil

      - name: Install dependencies
        run: npm ci || npm install

      # macOS Intel + Apple Silicon in einem Schritt
      - name: Build macOS (x64 + arm64)
        run: npx electron-builder --mac --x64 --arm64 --publish always

  build-windows:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build (Windows)
        run: npm run dist -- --publish always
