name: Build desktop apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci || npm install
      - name: Build (Windows)
        run: npm run dist
      - name: Upload artifact (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: wcag-checklist-win
          path: |
            dist/*.exe
            dist/*.msi
            dist/*.zip

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci || npm install
      - name: Build (macOS)
        run: npm run dist
      - name: Upload artifact (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: wcag-checklist-mac
          path: |
            dist/*.dmg
            dist/*-mac.zip
